start /b py gballot5.py 1
start /b py gballot5.py 2
start /b py gballot5.py 3
start /b py gballot5.py 4
start /b py gballot5.py 5
start /b py gballot5.py 6
start /b py gballot5.py 7
start /b py gballot5.py 8
start /b py gballot5.py 9
start /b py gballot5.py 10
start /b py gballot5.py 11
start /b py gballot5.py 12
start /b py gballot5.py 13
